# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: 9.0.x

         - name: Install Maui andriod workload
           run: dotnet workload install maui-android

         - name: List installed MAUI workload(s)
           run: dotnet workload list

         - name: Install OpenJDK 11
           run: |
              ubuntu_release=`lsb_release -rs`
              wget https://packages.microsoft.com/config/ubuntu/${ubuntu_release}/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
              sudo dpkg -i packages-microsoft-prod.deb
              sudo apt-get install apt-transport-https
              sudo apt-get update
              sudo apt-get install msopenjdk-11

         - name: Restore dependencies
           run: dotnet restore
           working-directory: .

         - name: Build application
           run: dotnet build --no-restore
           working-directory: .

         - name: Test
           run: dotnet test --no-build --verbosity normal
